"""change datetime to date

Revision ID: d48bec3db79e
Revises: e16f6244da53
Create Date: 2026-05-04 12:22:51.520983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd48bec3db79e'
down_revision: Union[str, Sequence[str], None] = 'e16f6244da53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'birthday',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_constraint(op.f('contacts_email_key'), 'contacts', type_='unique')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_unique_constraint(op.f('contacts_email_key'), 'contacts', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('contacts', 'birthday',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
